delimiter $$

DROP USER nuus$$

DROP DATABASE IF EXISTS `nuus`$$

CREATE DATABASE `nuus` /*!40100 DEFAULT CHARACTER SET utf8 */$$
CREATE USER nuus IDENTIFIED BY 'nuus'$$
GRANT ALL PRIVILEGES ON nuus.* TO 'nuus' WITH GRANT OPTION$$